# baseurl = "http://127.0.0.1:8000/"
relativeURLs = true
languageCode = "en-us"
title = "Test Pyramid"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Jesper Thomschutz"
	description = "Explaining what the Test Pyramid is and why it matters. Educational reference powered by community contributions."
	copyright = "Released under the Creative Commons Attribution-NonCommercial 3.0 Unported (CC BY-NC 3.0)"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/MonkeyTestIt/test-pyramid"

	version = "0.0.1"
	logo = "images/logo.svg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "monkeytestit"
	github  = "monkeytestit/test-pyramid"
	# email   = "human@monkeytest.it"


[[menu.main]]
	name   = "Material"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Adding content"
	url    = "adding-content/"
	weight = 20

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
